### ISSUE TITLE
IAM 생성시 경고 문구 추가

### ISSUE THREAD

**Issue by tonyfromundefined** [cadenzah/ausg-2020-handson-appsync#1]
<img width="750" alt="스크린샷 2020-01-09 오후 12 27 25" src="https://user-images.githubusercontent.com/20325202/72035504-6dd31c80-32db-11ea-8b3a-ebe5082cdce8.png">

이전에 제가 핸즈온 했던 자료에서는 IAM에서 경고 문구를 항상 넣었어요! 50명정도 규모의 핸즈온 하면 1,2명은 꼭 Git에 커밋하는 일이 있으니 경고 문구 반드시 포함해주세요.

**Comment by cadenzah** [comment]
아하 그렇네요! 이 내용은 꼭 포함시켜야겠군요.
