### ISSUE TITLE
나의 웹 서비스 -> 나의 서비스

### ISSUE THREAD

**Issue by yebonkim** [cadenzah/ausg-2020-handson-appsync#11]
ㅎㅎㅎ 너무 사소한 건데요

https://github.com/cadenzah/ausg-2020-handson-appsync/blob/master/handson/01.introduction.md

서비스 자원들을 사용하여 나의 웹 서비스를 구성할 수 있습니다. -> 나의 서비스를 구성할 수 있습니다.

라고 하면 좋을 것 같아요

모바일에서도 쓸 수 있으니까용...!

**Comment by cadenzah** [comment]
모바일 및 웹 앱이니까... 사소하지 않네요ㅎㅎㅎ 반영하겠습니다! 감사합니다..
