### ISSUE TITLE
오타 관련

### ISSUE THREAD

**Issue by yebonkim** [cadenzah/ausg-2020-handson-appsync#13]
https://github.com/cadenzah/ausg-2020-handson-appsync/blob/master/handson/02.settings.md  

- 확인하지 -> 확인하기

- 여기서 사용하는 액시스 키와 비밀 액세스 키는 앞서 -> 엑세스 키?

위 2개 오타 발견하였습니다!

나머지 페이지는 다 읽어봤을 때 오타 없는 것 같았어요~

**Comment by cadenzah** [comment]
와우 완전 꼼꼼하게 봐주셨네요.. 감사합니다
