### ISSUE TITLE
초반 부분 (part 2) 버전 관련 안내 

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#14]
버전이 완벽하게 최신버전이 아니어도 괜찮다고 언급하는게 어떨까요?

즉, **aws-cli가 적당히 1.xx.xx이고 node 가 적당히 12.xx.xx이고 npm 이 적당히 6.xx.xx이면 충분하다**는 말을 언급하는게 좋을 것 같습니다.

이렇게 해야 한다고 생각한 이유는 이미 node나 npm이 설치된 수강자가 "다시 업데이트 해야되는건가"하는 불안을 가질 수 있기 때문입니다.

**Comment by roeniss** [comment]
https://github.com/cadenzah/ausg-2020-handson-appsync/blob/master/handson/02.settings.md

**Comment by cadenzah** [comment]
맞습니다ㅎㅎ 버전이 다 다를수 있으니 실습자가 이에 대해 불안해할까봐 버전명을 리드미에 명시한거고... 실습할때 언급을 꼭 할 생각입니다
node는 큰 상관 없는데 aws-cli와 amplify는 버전 따라 문구나 실행시 질문이 바뀌기도 하니 언급을 하는게 좋겠네요

**Comment by cadenzah** [comment]
Node의 경우 바이너리 버전에 따라 npm 모듈 중 일부(sass)가 다르게 설치되므로, npm install 이후 노드 버전 변경 지양해달라는 문구 추가
