### ISSUE TITLE
어느 폴더에서 실행해야 하는지 명시

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#15]
https://github.com/cadenzah/ausg-2020-handson-appsync/blob/master/handson/03.react.md#2-amplify-project-%EC%B4%88%EA%B8%B0%ED%99%94 

`ausg-2020-handson-appsync` 폴더 들어온 후에 치는게 좋다고 얘기해야될 것 같습니다

```bash
D:\coding\tmp\ausg-2020-handson-appsync>amplify init
Note: It is recommended to run this command from the root of your app directory
```
라고 뜨네요

**Comment by cadenzah** [comment]
저 단계에다가 폴더 진입후 실행하라는 말을 적긴 해야겠군요. 혹시나 모르니...
(저 Note는 `amplift init` 실행할 때 항상 뜨긴 합니다)
