### ISSUE TITLE
설명 방식에 대한 건의사항

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#17]
part 1에서 Amplify 에 대한 개념을 확실하게 짚고 넘어가는게 좋을 것 같습니다.

즉, "Amplify는 회원가입/로그인 (인증), 데이터 저장 (DB), 호스팅 (Hosting) 등 '앱 만드는 데에 꽤나 빈번하게 사용되는 혹은 거의 필수적인 기능들'을 쉽게 생성하고 연동하도록 도와주는, **일종의 AWS 매니저 역할**이다" 정도로 설명하는 것이 어떨까 싶습니다.

이렇게 건의하게 된 것은 두 가지 이유가 있습니다.

 - 파트1에서, AppSync와 Amplify가 마치 동등한 위계(?) 서비스인 것처럼 묘사되어 있습니다. Amplify는 AppSync를 쉽게 쓸 수 있는 도우미 역할인데 말이지요. 
 - 파트 2에서, `amplify add api`를 하기 전에 `amplify add hosting`을 먼저 해서 "Amplify의 역할이 부품들을 쉽게 조립하는 것이며, 그 중 하나가 (바로 이) 호스팅이다. 이와 같이 api 기능도 한 번 붙여보자" 식으로 가는 게 어떨까 하는 생각이 들었습니다.

2번 이유는 따로 이슈를 남기겠습니다.

(이미 잘 하실거라 믿지만, 제가 '개인적으로' 대충 이해했다고 착각하고 넘어갔다가, 이해하는데 오래 걸려서요. 기우입니다ㅎㅎ)

**Comment by roeniss** [comment]
2번 이유에 관련된 추가 이슈: https://github.com/cadenzah/ausg-2020-handson-appsync/issues/18

**Comment by cadenzah** [comment]
Amplify와 AppSync랑 같은 위계로 느껴지게 설명이 이루어지면 분명 듣는분들이 헷갈려하겠죠!
이론에서 Amplify 설명할 때에 그 내용을 제대로 짚고 넘어가야겠네요. Amplify는 AppSync같은 작은 서비스들로 구성된다는 내용...
