### ISSUE TITLE
amplify에서 추가할 수 있는 모듈 리스트를 보여주는 게 어떨까요

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#18]
`amplify help` 명령어를 치면 제일 상단에 
```bash
| Category      |
| ------------- |
| analytics     |
| api           |
| auth          |
| function      |
| hosting       |
| interactions  |
| notifications |
| predictions   |
| storage       |
| xr            |
```
amplify에서 add 할 수 있는 모듈들이 나옵니다. 이 화면을 보여주면서 "hosting, aush, analytics등이 있는데 이 중 우리가 할 것이 api, 즉 graphql이다"라고 말해주는게 어떨까요?

ps. 원래는 amplify add hosting으로 호스팅 장면까지 보여주려고 했는데 appsync 에 대한 초점이 흐려지고 시간이 오버될 것 같습니다. (시간이 남으면 해봐도 좋을 듯 싶어요)

**Comment by cadenzah** [comment]
> amplify에서 add 할 수 있는 모듈들이 나옵니다. 이 화면을 보여주면서 "hosting, aush, analytics등이 있는데 이 중 우리가 할 것이 api, 즉 graphql이다"라고 말해주는게 어떨까요?

요것이 아주 정확한 핵심입니다ㅎㅎ 앞서서 이론할 때 amplify 설명하면서 한번 언급할 예정이긴 하고, amplify 사용하면서도 다시 언급은 할 생각이에요.

원래는 react 프론트를 `amplify add hosting`으로 해서 올리는 것도 함께 해볼까 생각했었는데, 어디까지나 이 핸즈온은 appsync 관련 핸즈온이니까, 로컬 서버로 실행시키는 정도로만 끝내고, s3로 호스팅할 수도 있다는 건 언급만 하고 넘어가기로 계획했습니다.

**Comment by cadenzah** [comment]
모듈 리스트를 보여주면서 이번 핸즈온에서 사용할 것만 집어서 설명하는 건 이해에 도움이 될 듯 하군요!

**Comment by cadenzah** [comment]
모듈 리스트가 나오는 것을 활용하여 Amplify가 제공하는 기능들을 소개하는 내용을 마지막 **더 알아보기** 섹션을 만들어서 추가했습니다. 좋은 아이디어 제공 감사합니다~
