### ISSUE TITLE
schema  파일이 자동으로 열리지 않는게 문제가 될까요?

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#19]
https://github.com/cadenzah/ausg-2020-handson-appsync/blob/master/handson/03.react.md#graphql-api-%EC%B6%94%EA%B0%80

윈도우에서는 (아래쪽에 코멘트 하신대로) 여기에서 `\ausg-2020-handson-appsync\amplify\backend/api/graphql/schema.graphql`가 자동으로 열리지 않습니다(vscode).

여기서 아무생각없이 (별다른 창이 뜨지 않으므로) Enter, Enter 눌러서 Interactive를 종료하는 사람도 있을 것 같은데, 이게 문제가 될까요? **만약 그렇다면 `amplify add api` 창에 진입하기 전에 경고를 주면 될 것 같습니다.**

**Comment by cadenzah** [comment]
확인해보니, `schema.graphql`을 수정하지 않은 상태에서 엔터 눌러서 interactive prompt 종료 후에 스키마를 수정해도 문제가 없네요!
해당 안내를 그 단계에 추가해두겠습니다. 좋은 제보 감사~
