### ISSUE TITLE
graphQL 에 대한 짤막한 설명을 하는 시간이 있나요?

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#20]
만약 없다면 파트 3에서 `schema.graphql`을 수정할 때 이게 무슨 의미의 코드인지 설명해주시면 좋을 것 같습니다!

**Comment by cadenzah** [comment]
이론할 때에 GraphQL 스키마 관련된 설명을 한번 할거고 (핵심적인 것만)
실습하면서도 `amplify add api`할 때에 직접 `schema.graphql` 파일을 작성하면서 설명을 곁들일 생각입니다!

스키마 자체는 GraphQL이 뭔지 할번 알고 나면 바로 이해할 수 있는 정도의 간단한 구조이니 굳이 넣지는 않았습니다. 핸즈온 과정에 대한 설명으로도 이미 꽤 긴데 거기에 graphql 관련 설명까지 넣으면 너무 길어질까 싶어서...

**Comment by roeniss** [comment]
그렇군요! 저는 개인적으로 GraphQL가 React 처음 볼 때랑 비슷한 느낌의 "기존에 접해보지 못한 새로운 접근"이어서, 납득하는 데(?) 좀 많이 버거웠어요. 잘부탁드립니다!

**Comment by cadenzah** [comment]
처음 graphql을 접할 때를 생각해보며... 최대한 느낌을 알아가실 수 있도록 잘 설명을 해야겠군요
AppSync로 API를 만들고나서 AppSync 콘솔을 쭉 돌아보며 GraphQL과 연관지어서 설명하는 것도 진행할 계획입니다

**Comment by roeniss** [comment]
^^ 180분의 전사들 출동..
