### ISSUE TITLE
첫 amplify push 과정에서 에러 발생하는 경우가 있음

### ISSUE THREAD

**Issue by roeniss** [cadenzah/ausg-2020-handson-appsync#21]
정확한 원인은 못찾았는데, `amplify push`를 하고, `amplify status`를 했는데 AppSync가 제대로 등록이 안되는 경우가 있습니다.

두 가지 증상으로 확인할 수 있습니다.

1. 아래 화면이 안뜹니다 (무한 로딩)
![image](https://user-images.githubusercontent.com/26613280/72280648-29010a00-367c-11ea-9a72-ab63b2087008.png)

2. AppSync 화면에서 아래 화면만 보게 됩니다 (API 추가가 안되어있음)
![image](https://user-images.githubusercontent.com/26613280/72280716-4e8e1380-367c-11ea-938f-584a4599652f.png)

해결방법은 `amplify remove api` 후 다시 add 부터 반복하는 것입니다.

재시도 전, 리전을 잘못 선택한 경우일 수도 있으니 한 번 더 확인하는 게 좋을 것 같습니다.

**Comment by cadenzah** [comment]
와우... 이런적 한번도 없었는데,,, 제보 너무나 감사합니다
혹시나 진행하다 오류가 생기면 이렇게 유도해야겠군요

**Comment by roeniss** [comment]
네네 아쉽게도 제가 관련 스크린샷을 못찍었네요. 현장에서 잘 대처해야겠어
