### ISSUE TITLE
s3 뿐 아니라 amplify 도 수동으로 제거해주어야 합니다.

### ISSUE THREAD

**Issue by asideHazle** [cadenzah/ausg-2020-handson-appsync#23]
기존 S3 뿐 아니라 Amplify에서 backend로 생성되는데 delete 시 같이 제거되지 않습니다.

해당 사항도 추가로 안내드리면 좋을것같습니다.

![amplify](https://user-images.githubusercontent.com/35303552/72663934-4e569500-3a3b-11ea-82e7-614cb7984909.png)

**Comment by cadenzah** [comment]
@asideHazle 안녕하세요, 우선 제보 감사드립니다.
세션을 준비하는 과정에서 충분히 확인을 하지 않고 진행했던 점 사과드립니다.
말씀해주신 내용을 토대로 안내를 문서에 추가하고, 다른 분들께도 안내를 드리도록 조치하겠습니다.
