### ISSUE TITLE
export alias 설정

### ISSUE THREAD

**Issue by tonyfromundefined** [cadenzah/ausg-2020-handson-appsync#3]
`index.js`로 폴더 내 자원들을 Alias 처리하는게 JS 초심자들은 이해하기 힘들 수 있어요. 없애는 방향이 좋다고 생각해요.

------
만약에 포함한다고 하면 다음과 같이 리팩토링하는건 어때요?
폴더명: `graphql` → `queries`로 변경

```javascript
// src/queries/getTodoList.js
export const getTodoList = `
  query GetTodoList {
    listTodos {
      items {
        id
        desc
        status
        date
      }
    }
  }
`
```

```javascript
// src/queries/index.ts
export import * from './getTodoList'
```

**Comment by cadenzah** [comment]
저도 이 부분은 고민을 했어요. JS가 익숙하지 않은 분들은 이런 사용법이 낯설 텐데 말이죠. 흠..
하나씩 import 하는게 진행이 더 매끄러울 것 같네요. 그런 방향으로 수정하는게 나을 것 같아요!
폴더명도 `queries`가 더 직관적인거같네요.
감사합니다! 😄

**Comment by tonyfromundefined** [comment]
핸즈온 자료로는 지금 좋은데요! 혹시 @cadenzah님이 GraphQL 실 서비스 클라이언트 만드신다면 Query를 손으로 import 하지 마시고, GraphQL Code Generator 꼭 쓰셔요~~

**Comment by cadenzah** [comment]
아하... 새로운 것 또 알아가네요! 감사합니다~ TS도 어서어서 정복해야겠군요...
